if: tag IS present OR branch = main

jobs:
  include:
    - dist: focal
      language: ruby

    - dist: trusty
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-25.0.2

install: skip
